### PR TITLE
Issue 16: Add unit tests

### LINKED ISSUE #16: Add unit tests
Need to add unit tests in order to make this application more reliable.

### PR DESCRIPTION
**Pull request by InfoSec812**
Resolved #16 

The code has been extensively refactored to enable unit testing.

I would greatly appreciated some testing and review of the changes!!

@tommybananas 
@dwinchell 
@TazSp

### CODE REVIEW

**Comment by InfoSec812** [comment]
For some reason, whenever `--ignore-dev-dependencies` is passed, I see JSON output. I cannot seem to trace the cause. WEIRD!

**Comment by InfoSec812** [comment]
Aha!!! Found and fixed the problem. It was an issue with function arity and I was passing too many arguments in some places.

**Comment by InfoSec812** [comment]
For anyone interested in testing this new version before it's published to NPM:

These command MAY require `sudo`
```
npm uninstall -g npm-audit-ci-wrapper
npm install -g git+https://github.com/InfoSec812/npm-audit-ci-wrapper.git#Issue_16_-_Add_unit_tests
```

**Comment by dwinchell** [comment]
Very nice. The tests pass for me and this branch finds the same results on my project as the master branch.

Looks good to me.

**Pull request merged**
